### ISSUE TITLE
Cannot find native static library Live2DCubismCore

### ISSUE THREAD

**Issue by Moebytes** [vss-project/godot-cubism#2]
I try to build this project but it says that it cannot find the native static library Live2DCubismCore. I put cubism-rs as well as the Core and Samples folders of Live2D native SDK into the third party folder.

Also I am on Mac and you did not provide build instructions for Mac, but I suppose that setting the target to `x86_64-apple-darwin` should be enough.

**Comment by you-win** [comment]
The build instructions from the upstream [cubism-rs](https://github.com/you-win/cubism-rs/tree/5bb327b85ed3826d305d3e29b68a961a759691bc) should be followed.

Note that there are special considerations made for OSX, [namely that static linking must be used](https://github.com/you-win/cubism-rs/blob/5bb327b85ed3826d305d3e29b68a961a759691bc/cubism-core-sys/build.rs#L33).

**Comment by Moebytes** [comment]
There are no build instructions in that repo, It just says to set `CUBISM_CORE` to the third party folder, which I see is already done in the sh script. Also, I believe that static linking is used by default. This is the full output:
<img width="1112" alt="Screen Shot 2022-08-15 at 5 47 05 PM" src="https://user-images.githubusercontent.com/37512637/184724274-40a30d74-3201-4c71-a76b-748efa205fa5.png">

**Comment by you-win** [comment]
Ah I should've been clearer, I was referring to the [instructions under the "General Usage Notes" section](https://github.com/you-win/cubism-rs/blob/5bb327b85ed3826d305d3e29b68a961a759691bc/cubism-core-sys/build.rs#L33). Namely, the part talking about setting an environment variable called `CUBISM_CORE` to the path to the static library.

In any case, this library is not fit for usage just yet. There are still problems with rendering Live2D models due to how Godot does not expose the stencil buffer to user code.

**Comment by Moebytes** [comment]
Do you mean like this? However it still gets the same error.
```
CUBISM_CORE=$(pwd)/third-party/Core/lib/macos/arm64/libLive2DCubismCore.a
```

Also I want to know if this lets me load Live2D models in Godot and animate their parameters in the editor or if its something else. I like using Live2D to animate and it would help my workflow if i can just import models into Godot instead of animating in Live2D and exporting the image sequence. Thanks!

**Comment by you-win** [comment]
Regarding the build errors, I would need to look into this more. The last commit in this repo is the last time I worked with this code. Most of this is new territory for me as well.

> Also I want to know if this lets me load Live2D models in Godot and animate their parameters in the editor
This is meant for displaying a Live2D model and animating it with face tracking data. In either case, this library is not ready for use because of the aforementioned rendering issues.

If you are trying to hack on this project, I'm happy to explain the design choices. However, my time is mostly devoted to the related [vpuppr](https://github.com/virtual-puppet-project/vpuppr) and [real-time-lip-sync](https://github.com/virtual-puppet-project/real-time-lip-sync-gd) projects at this point.

**Comment by Moebytes** [comment]
Ah, so this isn't what I was looking for. However I appreciate the help and good luck on your other projects!
